version: '3'

services:
  ubuntu:
    build:
      context: ./ubuntu
      dockerfile: Dockerfile
    ports:
      # - "12680:12680" # Billing port
      - "7384:7384" # Server port (serverlist.txt)
      - "3731:3731"
      - "8880:8880"
      - "8882:8882"
    volumes:
      - ./workspace/server:/home/tlbb
    links:
      - mysql
    restart: always
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "tlbb1234"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "tlbbdb"
    restart: always
  web:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./workspace/website:/var/www

